# Generated by Django 5.2.13 on 2026-05-08 05:54

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("changes", "0006_changerecord_emergency_declared_at_and_more"),
        ("evidence", "0001_initial"),
        ("organizations", "0004_membership_operator_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlMappingProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("soc2", "SOC 2"),
                            ("iso27001", "ISO 27001"),
                            ("nist", "NIST"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("mapping_rules", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_control_mapping_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control_mapping_profiles",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_control_mapping_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChangeControlCoverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("soc2", "SOC 2"),
                            ("iso27001", "ISO 27001"),
                            ("nist", "NIST"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("control_id", models.CharField(max_length=128)),
                ("control_title", models.CharField(blank=True, max_length=255)),
                (
                    "coverage_status",
                    models.CharField(
                        choices=[
                            ("covered", "Covered"),
                            ("partially_covered", "Partially Covered"),
                            ("not_covered", "Not Covered"),
                            ("not_applicable", "Not Applicable"),
                            ("stale", "Stale"),
                        ],
                        max_length=32,
                    ),
                ),
                ("matched_sections", models.JSONField(default=list)),
                ("missing_sections", models.JSONField(default=list)),
                ("evidence_paths", models.JSONField(default=list)),
                ("coverage_fingerprint_sha256", models.CharField(max_length=64)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "change_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control_coverages",
                        to="changes.changerecord",
                    ),
                ),
                (
                    "computed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="computed_control_coverages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidence_bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control_coverages",
                        to="evidence.evidencebundle",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_control_coverages",
                        to="organizations.organization",
                    ),
                ),
                (
                    "mapping_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverages",
                        to="auditor.controlmappingprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalChangeReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("servicenow", "ServiceNow"),
                            ("jira", "Jira"),
                            ("pagerduty", "PagerDuty"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("ticket", "Ticket"),
                            ("incident", "Incident"),
                            ("problem", "Problem"),
                            ("cmdb_ci", "CMDB CI"),
                            ("release", "Release"),
                        ],
                        max_length=32,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("external_key", models.CharField(blank=True, max_length=255)),
                ("display_label", models.CharField(max_length=255)),
                ("external_url", models.URLField(blank=True, max_length=2048)),
                ("snapshot", models.JSONField(default=dict)),
                ("snapshot_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "snapshot_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("api_refresh", "API Refresh"),
                            ("imported", "Imported"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                (
                    "snapshot_status",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("stale", "Stale"),
                            ("refresh_failed", "Refresh Failed"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="current",
                        max_length=32,
                    ),
                ),
                ("snapshot_taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_refresh_attempted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_refresh_error_code",
                    models.CharField(blank=True, max_length=64),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "change_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_references",
                        to="changes.changerecord",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_external_change_references",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_change_references",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCatalogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_key", models.SlugField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("owner_team", models.CharField(blank=True, max_length=255)),
                ("business_owner", models.CharField(blank=True, max_length=255)),
                ("criticality", models.CharField(blank=True, max_length=32)),
                ("environment", models.CharField(blank=True, max_length=64)),
                ("target_patterns", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_service_catalog_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_catalog_entries",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_service_catalog_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditorAccessGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("scope", models.JSONField(default=dict)),
                ("reason", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_auditor_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditor_access_grants",
                        to="organizations.organization",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_auditor_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditor_access_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "user", "status"],
                        name="aud_grant_org_user_status_idx",
                    ),
                    models.Index(
                        fields=["organization", "status", "expires_at"],
                        name="aud_grant_org_status_exp_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["active", "expired", "revoked"])
                        ),
                        name="aud_grant_status_valid_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "revoked"), _negated=True),
                            ("revoked_at__isnull", False),
                            _connector="OR",
                        ),
                        name="aud_grant_revoked_at_chk",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="controlmappingprofile",
            index=models.Index(
                fields=["organization", "standard", "is_active"],
                name="aud_ctrl_profile_org_std_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlmappingprofile",
            constraint=models.UniqueConstraint(
                fields=("organization", "key", "version"),
                name="aud_ctrl_profile_org_key_ver_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlmappingprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("standard__in", ["soc2", "iso27001", "nist", "custom"])
                ),
                name="aud_ctrl_profile_standard_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlmappingprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("organization", "standard", "key"),
                name="aud_ctrl_profile_one_active",
            ),
        ),
        migrations.AddIndex(
            model_name="changecontrolcoverage",
            index=models.Index(
                fields=["organization", "standard", "control_id"],
                name="aud_ctrl_cov_org_std_id_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="changecontrolcoverage",
            index=models.Index(
                fields=["organization", "change_record", "standard"],
                name="aud_ctrl_cov_org_chg_std_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="changecontrolcoverage",
            index=models.Index(
                fields=["organization", "coverage_status"],
                name="aud_ctrl_cov_org_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="changecontrolcoverage",
            constraint=models.UniqueConstraint(
                fields=("evidence_bundle", "mapping_profile", "control_id"),
                name="aud_ctrl_cov_bundle_profile_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="changecontrolcoverage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("standard__in", ["soc2", "iso27001", "nist", "custom"])
                ),
                name="aud_ctrl_cov_standard_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="changecontrolcoverage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "coverage_status__in",
                        [
                            "covered",
                            "partially_covered",
                            "not_covered",
                            "not_applicable",
                            "stale",
                        ],
                    )
                ),
                name="aud_ctrl_cov_status_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="externalchangereference",
            index=models.Index(
                fields=["organization", "system", "reference_type"],
                name="aud_ext_ref_org_sys_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="externalchangereference",
            index=models.Index(
                fields=["organization", "external_key"], name="aud_ext_ref_org_key_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalchangereference",
            index=models.Index(
                fields=["change_record", "system"], name="aud_ext_ref_change_sys_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalchangereference",
            constraint=models.UniqueConstraint(
                fields=(
                    "organization",
                    "change_record",
                    "system",
                    "reference_type",
                    "external_id",
                ),
                name="aud_ext_ref_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalchangereference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("system__in", ["servicenow", "jira", "pagerduty", "custom"])
                ),
                name="aud_ext_ref_system_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalchangereference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reference_type__in",
                        ["ticket", "incident", "problem", "cmdb_ci", "release"],
                    )
                ),
                name="aud_ext_ref_type_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalchangereference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("snapshot_source__in", ["manual", "api_refresh", "imported"])
                ),
                name="aud_ext_ref_source_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalchangereference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "snapshot_status__in",
                        ["current", "stale", "refresh_failed", "unavailable"],
                    )
                ),
                name="aud_ext_ref_snap_status_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="servicecatalogentry",
            index=models.Index(
                fields=["organization", "is_active", "service_key"],
                name="aud_svc_org_active_key_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicecatalogentry",
            index=models.Index(
                fields=["organization", "criticality"], name="aud_svc_org_crit_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecatalogentry",
            constraint=models.UniqueConstraint(
                fields=("organization", "service_key"),
                name="aud_svc_catalog_org_key_unique",
            ),
        ),
    ]
