# Generated by Django 5.2.13 on 2026-04-30 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('executions', '0006_alter_executionstep_status'),
        ('organizations', '0004_membership_operator_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approvaldecision',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['approved', 'rejected', 'timed_out'])), name='approval_dec_decision_valid_chk'),
        ),
        migrations.AddConstraint(
            model_name='approvaldecision',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['human', 'system'])), name='approval_dec_source_valid_chk'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected', 'timed_out'])), name='approval_req_status_valid_chk'),
        ),
    ]
