# Generated by Django 5.2.13 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0002_approvaldecision_approval_dec_decision_valid_chk_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["status", "requested_at"],
                name="approval_req_status_req_idx",
            ),
        ),
    ]
