# Generated by Django 5.2.13 on 2026-05-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0005_approval_subject_integrity_constraint"),
        ("executions", "0007_execution_exec_status_valid_chk_and_more"),
        ("organizations", "0004_membership_operator_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="approvalrequest",
            name="approval_req_subject_type_valid_chk",
        ),
        migrations.RemoveConstraint(
            model_name="approvalrequest",
            name="approval_req_subject_integrity_chk",
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("execution_step", "Execution Step"),
                    ("change_record", "Change Record"),
                    ("change_exception", "Change Exception"),
                ],
                default="execution_step",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "subject_type__in",
                        ["execution_step", "change_record", "change_exception"],
                    )
                ),
                name="approval_req_subject_type_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("execution_id__isnull", False),
                        ("step_id__isnull", False),
                        ("subject_type", "execution_step"),
                    ),
                    models.Q(
                        ("execution_id__isnull", True),
                        ("step_id__isnull", True),
                        ("subject_id__isnull", False),
                        ("subject_type", "change_record"),
                    ),
                    models.Q(
                        ("execution_id__isnull", True),
                        ("step_id__isnull", True),
                        ("subject_id__isnull", False),
                        ("subject_type", "change_exception"),
                    ),
                    _connector="OR",
                ),
                name="approval_req_subject_integrity_chk",
            ),
        ),
    ]
