import { useNavigate, useParams } from 'react-router-dom'

import { useAcceptWorkflowReview } from '../../features/workflows/hooks/useAcceptWorkflowReview'
import { useRejectWorkflowReview } from '../../features/workflows/hooks/useRejectWorkflowReview'
import { useWorkflowDetail } from '../../features/workflows/hooks/useWorkflowDetail'
import type { ActionInvocation, WorkflowDefinitionV2 } from '../../features/workflows/types'
import { getApiErrorMessage } from '../../shared/api/client'

function actionDetailText(action: ActionInvocation): string {
  const p = action.params
  if (!p) return '—'
  if (action.type === 'shell_command' && typeof p.command === 'string') return p.command
  if (action.type === 'http_request' && typeof p.method === 'string' && typeof p.url === 'string')
    return `${p.method} ${p.url}`
  if (action.type === 'manual_task' && typeof p.instructions === 'string') return p.instructions
  if (action.type === 'approval_gate' && typeof p.message === 'string') return p.message
  return '—'
}

export function WorkflowReviewPage() {
  const { workflowId } = useParams()
  const navigate = useNavigate()
  const workflowQuery = useWorkflowDetail(workflowId ?? null)
  const acceptReview = useAcceptWorkflowReview(workflowId ?? null)
  const rejectReview = useRejectWorkflowReview(workflowId ?? null)

  async function handleAccept() {
    await acceptReview.mutateAsync()
    navigate(`/workflows/${workflowId}`)
  }

  async function handleReject() {
    await rejectReview.mutateAsync()
    navigate('/runbooks')
  }

  const wf = workflowQuery.data
  const isV2 = wf?.definition_schema_version === 'workflow.schema.v2'

  return (
    <section className="panel stack-lg">
      <div className="panel__header">
        <p className="eyebrow">AI Review</p>
        <h2>Review AI-generated workflow</h2>
        <p className="muted">
          This workflow was generated by AI from a runbook document. Review the steps below before
          accepting or rejecting it.
        </p>
      </div>

      <p className="banner banner--warning">
        AI-generated workflow requires review before it can be published or executed.
      </p>

      {workflowQuery.isLoading ? <p className="muted">Loading workflow…</p> : null}
      {workflowQuery.error ? (
        <p className="banner banner--error">{getApiErrorMessage(workflowQuery.error)}</p>
      ) : null}

      {wf ? (
        <>
          <div className="detail-grid">
            <div>
              <p className="detail-grid__label">Name</p>
              <p>{wf.name}</p>
            </div>
            <div>
              <p className="detail-grid__label">Steps</p>
              <p>{wf.definition.steps.length}</p>
            </div>
            <div>
              <p className="detail-grid__label">Source</p>
              <p>{wf.parse_source === 'ai_parse' ? 'AI parsed' : 'Manual'}</p>
            </div>
            <div>
              <p className="detail-grid__label">Schema</p>
              <p>{wf.definition_schema_version}</p>
            </div>
          </div>

          <div className="stack-md">
            <h3>Steps</h3>
            {isV2 ? (
              <table className="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Action</th>
                    <th>Risk</th>
                    <th>Approval</th>
                    <th>Details</th>
                    <th>Secrets</th>
                  </tr>
                </thead>
                <tbody>
                  {(wf.definition as WorkflowDefinitionV2).steps.map((step, index) => (
                    <tr key={step.id}>
                      <td>{index + 1}</td>
                      <td>{step.name}</td>
                      <td>
                        <code className="code-inline">{step.action.type}</code>
                        {step.action.version ? (
                          <span className="muted" style={{ marginLeft: '0.3em', fontSize: '0.85em' }}>
                            v{step.action.version}
                          </span>
                        ) : null}
                      </td>
                      <td>
                        <span className={`pill pill--risk-${step.risk}`}>{step.risk}</span>
                      </td>
                      <td>{step.requiresApproval ? 'Required' : '—'}</td>
                      <td>
                        {actionDetailText(step.action) !== '—' ? (
                          <code className="code-inline">{actionDetailText(step.action)}</code>
                        ) : (
                          '—'
                        )}
                      </td>
                      <td>
                        {step.secrets?.length ? step.secrets.join(', ') : '—'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : (
              <table className="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Risk</th>
                    <th>Approval</th>
                    <th>Command</th>
                  </tr>
                </thead>
                <tbody>
                  {(wf.definition as { steps: import('../../features/workflows/types').WorkflowStep[] }).steps.map((step, index) => (
                    <tr key={step.id}>
                      <td>{index + 1}</td>
                      <td>{step.name}</td>
                      <td>{step.type}</td>
                      <td>
                        <span className={`pill pill--risk-${step.risk}`}>{step.risk}</span>
                      </td>
                      <td>{step.requiresApproval ? 'Required' : '—'}</td>
                      <td>
                        {step.command ? <code className="code-inline">{step.command}</code> : '—'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>

          <div className="actions-row">
            <button
              className="button"
              disabled={acceptReview.isPending || rejectReview.isPending}
              onClick={handleAccept}
              type="button"
            >
              {acceptReview.isPending ? 'Accepting…' : 'Accept workflow'}
            </button>
            <button
              className="button button--danger"
              disabled={acceptReview.isPending || rejectReview.isPending}
              onClick={handleReject}
              type="button"
            >
              {rejectReview.isPending ? 'Rejecting…' : 'Reject workflow'}
            </button>
          </div>

          {acceptReview.error ? (
            <p className="banner banner--error">{getApiErrorMessage(acceptReview.error)}</p>
          ) : null}
          {rejectReview.error ? (
            <p className="banner banner--error">{getApiErrorMessage(rejectReview.error)}</p>
          ) : null}
        </>
      ) : null}
    </section>
  )
}
