# Generated by Codex for Phase 10.3 audit trail.

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("runner", "Runner"),
                            ("system", "System"),
                            ("api_client", "API Client"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, max_length=255)),
                ("actor_label", models.CharField(blank=True, max_length=255)),
                ("event_type", models.CharField(max_length=128)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("runbook", "Runbook"),
                            ("workflow", "Workflow"),
                            ("execution", "Execution"),
                            ("execution_step", "Execution Step"),
                            ("approval_request", "Approval Request"),
                            ("approval_decision", "Approval Decision"),
                            ("policy", "Policy"),
                            ("policy_rule", "Policy Rule"),
                            ("policy_evaluation", "Policy Evaluation"),
                        ],
                        max_length=64,
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("organization_id", models.UUIDField()),
                ("metadata", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["organization_id", "occurred_at"],
                name="audit_org_occurred_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["object_type", "object_id", "occurred_at"],
                name="audit_object_occurred_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["event_type", "occurred_at"],
                name="audit_event_occurred_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["actor_type", "actor_id", "occurred_at"],
                name="audit_actor_occurred_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["organization_id", "event_type", "occurred_at"],
                name="audit_org_event_idx",
            ),
        ),
    ]
