# Generated by Django 5.2.13 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0004_auditevent_audit_actor_type_valid_chk_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["organization_id", "-occurred_at"],
                name="audit_org_occurred_desc_idx",
            ),
        ),
    ]
