# Generated by Django 5.2.13 on 2026-05-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_add_change_object_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='object_type',
            field=models.CharField(
                choices=[
                    ('organization', 'Organization'),
                    ('runbook', 'Runbook'),
                    ('workflow', 'Workflow'),
                    ('execution', 'Execution'),
                    ('execution_step', 'Execution Step'),
                    ('approval_request', 'Approval Request'),
                    ('approval_decision', 'Approval Decision'),
                    ('policy', 'Policy'),
                    ('policy_rule', 'Policy Rule'),
                    ('policy_evaluation', 'Policy Evaluation'),
                    ('artifact', 'Artifact'),
                    ('integration_connection', 'Integration Connection'),
                    ('operation_profile', 'Operation Profile'),
                    ('change_record', 'Change Record'),
                    ('change_target', 'Change Target'),
                    ('change_execution_binding', 'Change Execution Binding'),
                    ('change_window', 'Change Window'),
                    ('freeze_rule', 'Freeze Rule'),
                    ('target_lock', 'Target Lock'),
                    ('dispatch_eligibility_check', 'Dispatch Eligibility Check'),
                ],
                max_length=64,
            ),
        ),
    ]
