# Generated by Django 5.2.13 on 2026-05-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_remove_auditevent_audit_object_type_valid_chk_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditevent',
            name='audit_object_type_valid_chk',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='object_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('runbook', 'Runbook'), ('workflow', 'Workflow'), ('execution', 'Execution'), ('execution_step', 'Execution Step'), ('approval_request', 'Approval Request'), ('approval_decision', 'Approval Decision'), ('policy', 'Policy'), ('policy_rule', 'Policy Rule'), ('policy_evaluation', 'Policy Evaluation'), ('artifact', 'Artifact'), ('integration_connection', 'Integration Connection'), ('operation_profile', 'Operation Profile'), ('change_record', 'Change Record'), ('change_target', 'Change Target'), ('change_execution_binding', 'Change Execution Binding'), ('change_window', 'Change Window'), ('freeze_rule', 'Freeze Rule'), ('target_lock', 'Target Lock'), ('dispatch_eligibility_check', 'Dispatch Eligibility Check'), ('verification_plan', 'Verification Plan'), ('verification_check', 'Verification Check'), ('verification_result', 'Verification Result'), ('change_closure', 'Change Closure'), ('change_exception', 'Change Exception'), ('breakglass_session', 'Breakglass Session'), ('retro_review', 'Retro Review'), ('evidence_bundle', 'Evidence Bundle'), ('evidence_bundle_item', 'Evidence Bundle Item'), ('evidence_redaction_policy', 'Evidence Redaction Policy'), ('evidence_export', 'Evidence Export'), ('evidence_retention_policy', 'Evidence Retention Policy'), ('legal_hold', 'Legal Hold'), ('external_change_reference', 'External Change Reference'), ('service_catalog_entry', 'Service Catalog Entry'), ('control_mapping_profile', 'Control Mapping Profile'), ('change_control_coverage', 'Change Control Coverage'), ('auditor_access_grant', 'Auditor Access Grant')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(('object_type__in', ['organization', 'runbook', 'workflow', 'execution', 'execution_step', 'approval_request', 'approval_decision', 'policy', 'policy_rule', 'policy_evaluation', 'artifact', 'integration_connection', 'operation_profile', 'change_record', 'change_target', 'change_execution_binding', 'change_window', 'freeze_rule', 'target_lock', 'dispatch_eligibility_check', 'verification_plan', 'verification_check', 'verification_result', 'change_closure', 'change_exception', 'breakglass_session', 'retro_review', 'evidence_bundle', 'evidence_bundle_item', 'evidence_redaction_policy', 'evidence_export', 'evidence_retention_policy', 'legal_hold', 'external_change_reference', 'service_catalog_entry', 'control_mapping_profile', 'change_control_coverage', 'auditor_access_grant'])), name='audit_object_type_valid_chk'),
        ),
    ]
