# Generated by Django 5.2.13 on 2026-05-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("changes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerecord",
            name="workflow_definition_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
