# Generated by Django 5.2.13 on 2026-05-04 18:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("changes", "0002_add_workflow_definition_sha256"),
        ("executions", "0007_execution_exec_status_valid_chk_and_more"),
        ("organizations", "0004_membership_operator_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="changerecord",
            name="freeze_exception_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="changerecord",
            name="freeze_exception_recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changerecord",
            name="freeze_exception_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_freeze_exceptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="changerecord",
            name="freeze_exception_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="ChangeWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("open", "Open"),
                            ("expired", "Expired"),
                            ("overrun", "Overrun"),
                            ("closed", "Closed"),
                        ],
                        default="scheduled",
                        max_length=24,
                    ),
                ),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("reason", models.TextField(blank=True)),
                (
                    "approved_snapshot_sha256",
                    models.CharField(blank=True, max_length=64),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("overrun_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "change_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="window",
                        to="changes.changerecord",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_windows",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_change_windows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "starts_at"],
                        name="chgwin_org_status_start_idx",
                    ),
                    models.Index(
                        fields=["organization", "ends_at"],
                        name="change_window_org_ends_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["scheduled", "open", "expired", "overrun", "closed"],
                            )
                        ),
                        name="change_window_status_valid_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="change_window_ends_after_starts_chk",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DispatchEligibilityCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "result",
                    models.CharField(
                        choices=[("passed", "Passed"), ("failed", "Failed")],
                        max_length=16,
                    ),
                ),
                ("checked_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("approved_status_ok", models.BooleanField()),
                ("policy_pass_ok", models.BooleanField()),
                ("window_open_ok", models.BooleanField()),
                ("freeze_conflicts_ok", models.BooleanField()),
                ("target_locks_ok", models.BooleanField()),
                ("actor_authorized_ok", models.BooleanField()),
                ("checks", models.JSONField(default=list)),
                ("conflicts", models.JSONField(default=list)),
                ("input_snapshot_sha256", models.CharField(max_length=64)),
                ("window_snapshot_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "change_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eligibility_checks",
                        to="changes.changerecord",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_eligibility_checks",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_eligibility_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "change_record", "checked_at"],
                        name="dispatch_chk_org_chg_idx",
                    ),
                    models.Index(
                        fields=["organization", "result", "checked_at"],
                        name="dispatch_chk_org_res_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="dispatch_check_expires_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("result__in", ["passed", "failed"])),
                        name="dispatch_check_result_valid_chk",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FreezeRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "behavior",
                    models.CharField(
                        choices=[
                            ("block", "Block"),
                            ("allow_with_exception", "Allow With Exception"),
                        ],
                        max_length=32,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("all_production", "All Production"),
                            ("target_type", "Target Type"),
                            ("target_identifier", "Target Identifier"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_identifier", models.CharField(blank=True, max_length=255)),
                ("normalized_identifier", models.CharField(blank=True, max_length=255)),
                ("requires_exception_reference", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_freeze_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freeze_rules",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_freeze_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active", "starts_at", "ends_at"],
                        name="freeze_org_active_range_idx",
                    ),
                    models.Index(
                        fields=[
                            "organization",
                            "scope_type",
                            "target_type",
                            "normalized_identifier",
                        ],
                        name="freeze_org_scope_target_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("behavior__in", ["block", "allow_with_exception"])
                        ),
                        name="freeze_rule_behavior_valid_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "scope_type__in",
                                ["all_production", "target_type", "target_identifier"],
                            )
                        ),
                        name="freeze_rule_scope_type_valid_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="freeze_rule_ends_after_starts_chk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("behavior", "allow_with_exception"), _negated=True
                            ),
                            ("requires_exception_reference", True),
                            _connector="OR",
                        ),
                        name="freeze_rule_exception_behavior_requires_ref_chk",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TargetLock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_type", models.CharField(max_length=64)),
                ("target_identifier", models.CharField(max_length=255)),
                ("normalized_identifier", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=24,
                    ),
                ),
                ("acquired_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("release_reason", models.CharField(blank=True, max_length=64)),
                (
                    "change_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_locks",
                        to="changes.changerecord",
                    ),
                ),
                (
                    "change_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_locks",
                        to="changes.changetarget",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_locks",
                        to="executions.execution",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_locks",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "acquired_at"],
                        name="target_lock_org_status_acq_idx",
                    ),
                    models.Index(
                        fields=["change_record", "status"],
                        name="target_lock_change_status_idx",
                    ),
                    models.Index(
                        fields=["execution", "status"],
                        name="target_lock_exec_status_idx",
                    ),
                    models.Index(
                        fields=[
                            "organization",
                            "target_type",
                            "normalized_identifier",
                            "status",
                        ],
                        name="tlock_org_type_id_status_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["active", "released", "expired"])
                        ),
                        name="target_lock_status_valid_chk",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("organization", "target_type", "normalized_identifier"),
                        name="target_lock_active_unique",
                    ),
                ],
            },
        ),
    ]
