# Generated by Django 5.2.13 on 2026-05-05 17:44

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0005_approval_subject_integrity_constraint"),
        ("artifacts", "0001_initial"),
        ("changes", "0004_execution_timing_fields"),
        ("organizations", "0004_membership_operator_role"),
        ("policies", "0001_initial"),
        ("workflows", "0003_workflow_requires_review_parse_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeClosure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("rolled_back", "Rolled Back"),
                            ("partial_success", "Partial Success"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("summary", models.TextField()),
                ("verification_summary", models.JSONField(default=dict)),
                ("execution_summary", models.JSONField(default=dict)),
                ("closed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="VerificationCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField()),
                ("key", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("runner_step", "Runner Step"),
                            ("artifact_presence", "Artifact Presence"),
                            ("manual_attestation", "Manual Attestation"),
                            ("api_assertion", "API Assertion"),
                            ("external_reference", "External Reference"),
                        ],
                        max_length=32,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("verification_key", models.CharField(blank=True, max_length=128)),
                ("source_step_key", models.CharField(blank=True, max_length=128)),
                ("artifact_kind", models.CharField(blank=True, max_length=32)),
                ("artifact_name_pattern", models.CharField(blank=True, max_length=255)),
                (
                    "expected_checksum_sha256",
                    models.CharField(blank=True, max_length=64),
                ),
                ("api_assertion", models.JSONField(default=dict)),
                ("external_reference_config", models.JSONField(default=dict)),
                ("manual_attestation_config", models.JSONField(default=dict)),
                ("satisfied_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VerificationPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("automated", "Automated"),
                            ("manual", "Manual"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("active", "Active"),
                            ("satisfied", "Satisfied"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="generated",
                        max_length=24,
                    ),
                ),
                ("generated_from_profile_snapshot", models.JSONField(default=dict)),
                ("generated_from_profile_sha256", models.CharField(max_length=64)),
                ("required_check_count", models.PositiveIntegerField(default=0)),
                ("optional_check_count", models.PositiveIntegerField(default=0)),
                ("satisfied_required_count", models.PositiveIntegerField(default=0)),
                ("failed_required_count", models.PositiveIntegerField(default=0)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("satisfied_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VerificationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("runner", "Runner"),
                            ("user", "User"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("passed", "Passed"), ("failed", "Failed")],
                        max_length=16,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                        max_length=16,
                    ),
                ),
                ("runner_id", models.CharField(blank=True, max_length=255)),
                ("verification_key", models.CharField(blank=True, max_length=128)),
                (
                    "artifact_checksum_sha256",
                    models.CharField(blank=True, max_length=64),
                ),
                ("external_reference", models.CharField(blank=True, max_length=1024)),
                ("api_assertion_snapshot", models.JSONField(default=dict)),
                ("manual_attestation_text", models.TextField(blank=True)),
                ("observed_value", models.JSONField(default=dict)),
                ("validation_errors", models.JSONField(default=list)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "validated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="changerecord",
            name="change_rec_status_valid_chk",
        ),
        migrations.AddField(
            model_name="changerecord",
            name="verification_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationprofile",
            name="requires_independent_reviewer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="operationprofile",
            name="verification_mode",
            field=models.CharField(
                choices=[
                    ("automated", "Automated"),
                    ("manual", "Manual"),
                    ("mixed", "Mixed"),
                ],
                default="mixed",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="operationprofile",
            name="verification_plan_template",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="operationprofile",
            name="verification_timeout_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="changerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("dispatchable", "Dispatchable"),
                    ("running", "Running"),
                    ("verification_pending", "Verification Pending"),
                    ("verification_failed", "Verification Failed"),
                    ("verified", "Verified"),
                    ("closed", "Closed"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="changerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "draft",
                            "pending_approval",
                            "approved",
                            "scheduled",
                            "dispatchable",
                            "running",
                            "verification_pending",
                            "verification_failed",
                            "verified",
                            "closed",
                            "rejected",
                            "canceled",
                            "expired",
                        ],
                    )
                ),
                name="change_rec_status_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verification_mode__in", ["automated", "manual", "mixed"])
                ),
                name="op_profile_verif_mode_valid_chk",
            ),
        ),
        migrations.AddField(
            model_name="changeclosure",
            name="change_record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closure",
                to="changes.changerecord",
            ),
        ),
        migrations.AddField(
            model_name="changeclosure",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="changeclosure",
            name="independent_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="independently_reviewed_change_closures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="changeclosure",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_closures",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="verificationcheck",
            name="change_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verification_checks",
                to="changes.changerecord",
            ),
        ),
        migrations.AddField(
            model_name="verificationcheck",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verification_checks",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="verificationplan",
            name="change_record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verification_plan",
                to="changes.changerecord",
            ),
        ),
        migrations.AddField(
            model_name="verificationplan",
            name="operation_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verification_plans",
                to="changes.operationprofile",
            ),
        ),
        migrations.AddField(
            model_name="verificationplan",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verification_plans",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="verificationcheck",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checks",
                to="changes.verificationplan",
            ),
        ),
        migrations.AddField(
            model_name="changeclosure",
            name="verification_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closures",
                to="changes.verificationplan",
            ),
        ),
        migrations.AddField(
            model_name="verificationresult",
            name="artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verification_results",
                to="artifacts.artifact",
            ),
        ),
        migrations.AddField(
            model_name="verificationresult",
            name="change_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verification_results",
                to="changes.changerecord",
            ),
        ),
        migrations.AddField(
            model_name="verificationresult",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verification_results",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="verificationresult",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="changes.verificationplan",
            ),
        ),
        migrations.AddField(
            model_name="verificationresult",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_verification_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="verificationresult",
            name="verification_check",
            field=models.ForeignKey(
                db_column="check_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="changes.verificationcheck",
            ),
        ),
        migrations.AddField(
            model_name="verificationcheck",
            name="last_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="changes.verificationresult",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationplan",
            index=models.Index(
                fields=["organization", "status", "generated_at"],
                name="verif_plan_org_status_gen_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationplan",
            index=models.Index(
                fields=["operation_profile", "status"],
                name="verif_plan_profile_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode__in", ["automated", "manual", "mixed"])),
                name="verif_plan_mode_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["generated", "active", "satisfied", "failed", "canceled"],
                    )
                ),
                name="verif_plan_status_valid_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="changeclosure",
            index=models.Index(
                fields=["organization", "outcome", "closed_at"],
                name="chgclosure_org_out_closed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="changeclosure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome__in",
                        [
                            "success",
                            "rolled_back",
                            "partial_success",
                            "failed",
                            "canceled",
                        ],
                    )
                ),
                name="change_closure_outcome_valid_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationresult",
            index=models.Index(
                fields=["change_record", "validation_status", "submitted_at"],
                name="verif_result_chg_val_sub_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationresult",
            index=models.Index(
                fields=["verification_check", "validation_status", "submitted_at"],
                name="verif_result_check_val_sub_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationresult",
            index=models.Index(
                fields=["organization", "runner_id", "submitted_at"],
                name="verif_res_org_runner_sub_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationresult",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["runner", "user", "system"])),
                name="verif_result_source_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationresult",
            constraint=models.CheckConstraint(
                condition=models.Q(("outcome__in", ["passed", "failed"])),
                name="verif_result_outcome_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationresult",
            constraint=models.CheckConstraint(
                condition=models.Q(("validation_status__in", ["accepted", "rejected"])),
                name="verif_result_validation_valid_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcheck",
            index=models.Index(
                fields=["organization", "check_type", "status"],
                name="verif_chk_org_type_stat_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcheck",
            index=models.Index(
                fields=["change_record", "required", "status"],
                name="verif_check_chg_req_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationcheck",
            constraint=models.UniqueConstraint(
                fields=("plan", "key"), name="verif_check_plan_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationcheck",
            constraint=models.UniqueConstraint(
                fields=("plan", "position"), name="verif_check_plan_pos_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationcheck",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "check_type__in",
                        [
                            "runner_step",
                            "artifact_presence",
                            "manual_attestation",
                            "api_assertion",
                            "external_reference",
                        ],
                    )
                ),
                name="verif_check_type_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationcheck",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "passed", "failed", "not_applicable"])
                ),
                name="verif_check_status_valid_chk",
            ),
        ),
    ]
