# Generated by Django 5.2.13 on 2026-05-06 21:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_remove_approvalrequest_approval_req_subject_type_valid_chk_and_more'),
        ('artifacts', '0001_initial'),
        ('changes', '0005_changeclosure_verificationcheck_verificationplan_and_more'),
        ('organizations', '0004_membership_operator_role'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changerecord',
            name='emergency_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerecord',
            name='emergency_declared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_emergency_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerecord',
            name='emergency_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='changerecord',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='changerecord',
            name='retro_review_blocking_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='changerecord',
            name='retro_review_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerecord',
            name='retro_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationprofile',
            name='allow_emergency_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationprofile',
            name='max_breakglass_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationprofile',
            name='retro_review_sla_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BreakglassSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=24)),
                ('scope_json', models.JSONField()),
                ('scope_sha256', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=64)),
                ('review_due_at', models.DateTimeField()),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('overdue', 'Overdue'), ('blocked', 'Blocked')], default='pending', max_length=24)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('activation_ip_hash', models.CharField(blank=True, max_length=64)),
                ('activation_user_agent', models.CharField(blank=True, max_length=255)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_breakglass_sessions', to=settings.AUTH_USER_MODEL)),
                ('change_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakglass_sessions', to='changes.changerecord')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_breakglass_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakglass_sessions', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exception_type', models.CharField(choices=[('freeze_override', 'Freeze Override'), ('window_overrun', 'Window Overrun'), ('late_verification', 'Late Verification'), ('policy_override', 'Policy Override'), ('missing_artifact', 'Missing Artifact')], max_length=32)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('expired', 'Expired')], default='pending_approval', max_length=32)),
                ('reason', models.TextField()),
                ('scope_json', models.JSONField(default=dict)),
                ('requested_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_exceptions', to='approvals.approvalrequest')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_change_exceptions', to=settings.AUTH_USER_MODEL)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_exceptions', to='artifacts.artifact')),
                ('change_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='changes.changerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_exceptions', to='organizations.organization')),
                ('policy_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_exceptions', to='policies.policyevaluation')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_change_exceptions', to=settings.AUTH_USER_MODEL)),
                ('verification_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_exceptions', to='changes.verificationcheck')),
            ],
        ),
        migrations.CreateModel(
            name='RetroReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('superseded', 'Superseded')], default='pending', max_length=24)),
                ('disposition', models.CharField(blank=True, max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('remediation_required', models.BooleanField(default=False)),
                ('remediation_reference', models.CharField(blank=True, max_length=255)),
                ('control_failure_category', models.CharField(blank=True, max_length=64)),
                ('evidence_json', models.JSONField(default=dict)),
                ('breakglass_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retro_review', to='changes.breakglasssession')),
                ('change_exception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retro_reviews', to='changes.changeexception')),
                ('change_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retro_reviews', to='changes.changerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retro_reviews', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retro_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='breakglasssession',
            index=models.Index(fields=['organization', 'status', 'expires_at'], name='bglsess_org_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='breakglasssession',
            index=models.Index(fields=['organization', 'review_status', 'review_due_at'], name='bglsess_org_revstat_due_idx'),
        ),
        migrations.AddIndex(
            model_name='breakglasssession',
            index=models.Index(fields=['change_record', 'status'], name='bglsess_change_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='breakglasssession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'ended', 'expired', 'revoked'])), name='bglsess_status_valid_chk'),
        ),
        migrations.AddConstraint(
            model_name='breakglasssession',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['pending', 'submitted', 'accepted', 'overdue', 'blocked'])), name='bglsess_review_status_valid_chk'),
        ),
        migrations.AddConstraint(
            model_name='breakglasssession',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('started_at'))), name='bglsess_expires_after_started_chk'),
        ),
        migrations.AddConstraint(
            model_name='breakglasssession',
            constraint=models.CheckConstraint(condition=models.Q(('review_due_at__gte', models.F('started_at'))), name='bglsess_review_due_gte_started_chk'),
        ),
        migrations.AddConstraint(
            model_name='breakglasssession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('change_record',), name='bglsess_one_active_per_change'),
        ),
        migrations.AddIndex(
            model_name='changeexception',
            index=models.Index(fields=['organization', 'status', 'expires_at'], name='chgexc_org_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='changeexception',
            index=models.Index(fields=['change_record', 'exception_type', 'status'], name='chgexc_change_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='changeexception',
            index=models.Index(fields=['approval_request'], name='chgexc_approval_req_idx'),
        ),
        migrations.AddConstraint(
            model_name='changeexception',
            constraint=models.CheckConstraint(condition=models.Q(('exception_type__in', ['freeze_override', 'window_overrun', 'late_verification', 'policy_override', 'missing_artifact'])), name='chgexc_exception_type_valid_chk'),
        ),
        migrations.AddConstraint(
            model_name='changeexception',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending_approval', 'approved', 'rejected', 'resolved', 'expired'])), name='chgexc_status_valid_chk'),
        ),
        migrations.AddConstraint(
            model_name='changeexception',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('requested_at'))), name='chgexc_expires_after_requested_chk'),
        ),
        migrations.AddIndex(
            model_name='retroreview',
            index=models.Index(fields=['organization', 'status', 'due_at'], name='retrorev_org_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='retroreview',
            index=models.Index(fields=['change_record', 'status'], name='retrorev_change_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='retroreview',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'submitted', 'superseded'])), name='retrorev_status_valid_chk'),
        ),
        migrations.AddConstraint(
            model_name='retroreview',
            constraint=models.CheckConstraint(condition=models.Q(('disposition', ''), ('disposition__in', ['accepted', 'needs_remediation', 'control_failure']), _connector='OR'), name='retrorev_disposition_valid_chk'),
        ),
        migrations.AddConstraint(
            model_name='retroreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'submitted'), _negated=True), models.Q(('disposition', ''), _negated=True), _connector='OR'), name='retrorev_submitted_needs_disposition_chk'),
        ),
        migrations.AddConstraint(
            model_name='retroreview',
            constraint=models.CheckConstraint(condition=models.Q(('breakglass_session_id__isnull', False), ('change_exception_id__isnull', False), _connector='OR'), name='retrorev_source_required_chk'),
        ),
    ]
