# Generated by Django 5.2.13 on 2026-05-07 15:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artifacts", "0001_initial"),
        ("changes", "0006_changerecord_emergency_declared_at_and_more"),
        ("organizations", "0004_membership_operator_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compiling", "Compiling"),
                            ("sealed", "Sealed"),
                            ("invalidated", "Invalidated"),
                        ],
                        default="compiling",
                        max_length=24,
                    ),
                ),
                (
                    "completeness_status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("incomplete", "Incomplete"),
                            ("invalid", "Invalid"),
                        ],
                        default="incomplete",
                        max_length=24,
                    ),
                ),
                ("completeness_report", models.JSONField(default=dict)),
                ("source_snapshot_sha256", models.CharField(blank=True, max_length=64)),
                ("source_cutoff_at", models.DateTimeField()),
                ("source_high_watermark", models.JSONField(default=dict)),
                ("manifest", models.JSONField(default=dict)),
                ("manifest_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "payload_checksums_sha256",
                    models.CharField(blank=True, max_length=64),
                ),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "content_size_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("storage_key", models.CharField(blank=True, max_length=1024)),
                (
                    "mime_type",
                    models.CharField(default="application/zip", max_length=128),
                ),
                (
                    "compiled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("sealed_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("invalidation_reason", models.CharField(blank=True, max_length=128)),
                ("retention_expires_at", models.DateTimeField(blank=True, null=True)),
                ("storage_deleted_at", models.DateTimeField(blank=True, null=True)),
                ("storage_delete_reason", models.CharField(blank=True, max_length=128)),
                (
                    "change_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_bundles",
                        to="changes.changerecord",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_evidence_bundles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invalidated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invalidated_evidence_bundles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_bundles",
                        to="organizations.organization",
                    ),
                ),
                (
                    "previous_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseding_bundles",
                        to="evidence.evidencebundle",
                    ),
                ),
                (
                    "sealed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sealed_evidence_bundles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceRedactionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("rules", models.JSONField(default=list)),
                ("rules_sha256", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_evidence_redaction_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_redaction_policies",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_evidence_redaction_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "Creating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="creating",
                        max_length=24,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("storage_key", models.CharField(blank=True, max_length=1024)),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "content_size_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("manifest", models.JSONField(default=dict)),
                ("manifest_sha256", models.CharField(blank=True, max_length=64)),
                ("source_manifest_sha256", models.CharField(max_length=64)),
                ("source_bundle_content_sha256", models.CharField(max_length=64)),
                ("redaction_summary", models.JSONField(default=dict)),
                ("receipt", models.JSONField(default=dict)),
                ("receipt_sha256", models.CharField(blank=True, max_length=64)),
                ("failure_code", models.CharField(blank=True, max_length=128)),
                ("failure_message", models.TextField(blank=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("last_downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("storage_deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exports",
                        to="evidence.evidencebundle",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_exports",
                        to="organizations.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_evidence_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "redaction_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_exports",
                        to="evidence.evidenceredactionpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceRetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("sealed_bundle_retention_days", models.PositiveIntegerField()),
                ("invalidated_bundle_retention_days", models.PositiveIntegerField()),
                ("export_retention_days", models.PositiveIntegerField()),
                (
                    "cleanup_action",
                    models.CharField(
                        choices=[
                            (
                                "delete_content_keep_metadata",
                                "Delete Content Keep Metadata",
                            )
                        ],
                        default="delete_content_keep_metadata",
                        max_length=64,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_evidence_retention_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_retention_policies",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_evidence_retention_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evidencebundle",
            name="retention_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_bundles",
                to="evidence.evidenceretentionpolicy",
            ),
        ),
        migrations.CreateModel(
            name="LegalHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("released", "Released")],
                        default="active",
                        max_length=24,
                    ),
                ),
                ("reason", models.TextField(max_length=2000)),
                ("external_reference", models.CharField(blank=True, max_length=512)),
                ("placed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("release_reason", models.TextField(blank=True, max_length=2000)),
                (
                    "change_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_holds",
                        to="changes.changerecord",
                    ),
                ),
                (
                    "evidence_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_holds",
                        to="evidence.evidencebundle",
                    ),
                ),
                (
                    "evidence_export",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_holds",
                        to="evidence.evidenceexport",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_holds",
                        to="organizations.organization",
                    ),
                ),
                (
                    "placed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placed_legal_holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_legal_holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-placed_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceBundleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("change_snapshot", "Change Snapshot"),
                            ("approval", "Approval"),
                            ("policy_decision", "Policy Decision"),
                            ("execution", "Execution"),
                            ("audit_event", "Audit Event"),
                            ("artifact", "Artifact"),
                            ("verification_result", "Verification Result"),
                            ("closure", "Closure"),
                            ("exception", "Exception"),
                            ("external_reference", "External Reference"),
                            ("export_receipt", "Export Receipt"),
                        ],
                        max_length=32,
                    ),
                ),
                ("item_key", models.CharField(max_length=255)),
                ("canonical_path", models.CharField(max_length=512)),
                ("json_pointer", models.CharField(blank=True, max_length=512)),
                ("position", models.PositiveIntegerField(default=0)),
                ("required", models.BooleanField(default=True)),
                ("present", models.BooleanField(default=True)),
                ("valid", models.BooleanField(default=True)),
                ("missing_reason", models.CharField(blank=True, max_length=128)),
                ("validation_errors", models.JSONField(default=list)),
                ("source_type", models.CharField(blank=True, max_length=128)),
                ("source_id", models.CharField(blank=True, max_length=128)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("source_metadata", models.JSONField(default=dict)),
                ("staging_storage_key", models.CharField(blank=True, max_length=1024)),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "content_size_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_items",
                        to="artifacts.artifact",
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="evidence.evidencebundle",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_bundle_items",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["item_type", "position", "canonical_path", "item_key"],
                "indexes": [
                    models.Index(
                        fields=["organization", "item_type"],
                        name="ev_item_org_type_idx",
                    ),
                    models.Index(
                        fields=["bundle", "item_type", "position"],
                        name="ev_item_bundle_type_pos_idx",
                    ),
                    models.Index(fields=["artifact"], name="ev_item_artifact_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bundle", "item_type", "item_key"),
                        name="evidence_item_bundle_type_key_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("bundle", "canonical_path", "json_pointer", "item_key"),
                        name="evidence_item_bundle_path_ptr_key_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "item_type__in",
                                [
                                    "change_snapshot",
                                    "approval",
                                    "policy_decision",
                                    "execution",
                                    "audit_event",
                                    "artifact",
                                    "verification_result",
                                    "closure",
                                    "exception",
                                    "external_reference",
                                    "export_receipt",
                                ],
                            )
                        ),
                        name="evidence_item_type_valid_chk",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="evidenceredactionpolicy",
            index=models.Index(
                fields=["organization", "is_active", "name"],
                name="ev_redact_org_active_name_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceredactionpolicy",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="evidence_redaction_org_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceredactionpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("organization",),
                name="evidence_redaction_default_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceexport",
            index=models.Index(
                fields=["organization", "status", "requested_at"],
                name="ev_export_org_status_req_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceexport",
            index=models.Index(
                fields=["bundle", "requested_at"], name="ev_export_bundle_req_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceexport",
            index=models.Index(
                fields=["organization", "expires_at"], name="ev_export_org_expires_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceexport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storage_key", ""), _negated=True),
                fields=("storage_key",),
                name="evidence_export_storage_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceexport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["creating", "ready", "failed", "expired"])
                ),
                name="evidence_export_status_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceexport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "ready"), _negated=True),
                    models.Q(
                        ("ready_at__isnull", False),
                        models.Q(("storage_key", ""), _negated=True),
                        models.Q(("content_sha256", ""), _negated=True),
                        ("content_size_bytes__isnull", False),
                        models.Q(("manifest_sha256", ""), _negated=True),
                        models.Q(("receipt_sha256", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="evidence_export_ready_fields_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceretentionpolicy",
            index=models.Index(
                fields=["organization", "is_active", "name"],
                name="ev_retain_org_active_name_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceretentionpolicy",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="evidence_retention_org_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceretentionpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("organization",),
                name="evidence_retention_default_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceretentionpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("sealed_bundle_retention_days__gt", 0)),
                name="evidence_retention_sealed_days_gt0_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceretentionpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("invalidated_bundle_retention_days__gt", 0)),
                name="evidence_retention_invalid_days_gt0_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceretentionpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("export_retention_days__gt", 0)),
                name="evidence_retention_export_days_gt0_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceretentionpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("cleanup_action", "delete_content_keep_metadata")),
                name="evidence_retention_cleanup_valid_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencebundle",
            index=models.Index(
                fields=["organization", "change_record", "version"],
                name="ev_bundle_org_change_ver_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencebundle",
            index=models.Index(
                fields=["organization", "status", "created_at"],
                name="ev_bundle_org_status_cr_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencebundle",
            index=models.Index(
                fields=["organization", "completeness_status", "created_at"],
                name="ev_bundle_org_comp_cr_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencebundle",
            index=models.Index(
                fields=["organization", "retention_expires_at"],
                name="ev_bundle_org_ret_exp_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencebundle",
            constraint=models.UniqueConstraint(
                fields=("change_record", "version"),
                name="evidence_bundle_change_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencebundle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storage_key", ""), _negated=True),
                fields=("storage_key",),
                name="evidence_bundle_storage_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencebundle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["compiling", "sealed", "invalidated"])
                ),
                name="evidence_bundle_status_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencebundle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completeness_status__in", ["complete", "incomplete", "invalid"])
                ),
                name="evidence_bundle_completeness_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencebundle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "sealed"), _negated=True),
                    models.Q(
                        ("sealed_at__isnull", False),
                        models.Q(("manifest_sha256", ""), _negated=True),
                        models.Q(("content_sha256", ""), _negated=True),
                        ("content_size_bytes__isnull", False),
                        models.Q(("storage_key", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="evidence_bundle_sealed_fields_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencebundle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "invalidated"), _negated=True),
                    models.Q(
                        ("invalidated_at__isnull", False),
                        models.Q(("invalidation_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="evidence_bundle_invalid_fields_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="legalhold",
            index=models.Index(
                fields=["organization", "status", "placed_at"],
                name="ev_hold_org_status_place_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legalhold",
            index=models.Index(
                fields=["change_record", "status"], name="legal_hold_change_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalhold",
            index=models.Index(
                fields=["evidence_bundle", "status"], name="legal_hold_bundle_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalhold",
            index=models.Index(
                fields=["evidence_export", "status"], name="legal_hold_export_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalhold",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "released"])),
                name="legal_hold_status_valid_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalhold",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "released"), _negated=True),
                    models.Q(
                        ("released_at__isnull", False),
                        ("released_by__isnull", False),
                        models.Q(("release_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="legal_hold_release_fields_chk",
            ),
        ),
    ]
