# Generated by Django 5.2.13 on 2026-04-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runbooks", "0002_alter_runbook_raw_content_alter_runbook_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runbook",
            name="slug",
            field=models.SlugField(max_length=96),
        ),
    ]
