# Generated by Django 5.2.13 on 2026-04-15 21:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('runbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('definition_schema_version', models.CharField(default='1.0', max_length=20)),
                ('definition', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='organizations.organization')),
                ('runbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='runbooks.runbook')),
            ],
            options={
                'ordering': ['name', '-version'],
                'constraints': [models.UniqueConstraint(fields=('runbook', 'version'), name='unique_workflow_version_per_runbook'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='workflow_version_gte_1')],
            },
        ),
    ]
