# Generated by Django 5.2.13 on 2026-04-28 19:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_alter_organization_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("slack_webhook", "Slack Webhook"),
                            ("generic_webhook", "Generic Webhook"),
                            ("pagerduty", "PagerDuty"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("config", models.JSONField(default=dict)),
                ("encrypted_credentials", models.BinaryField(blank=True, null=True)),
                ("event_types", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_delivery_status",
                    models.CharField(
                        blank=True,
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=32,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_connections",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=64)),
                ("payload_preview", models.JSONField(default=dict)),
                ("http_status", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField()),
                ("error_detail", models.TextField(blank=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("attempted_at", models.DateTimeField()),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="integrations.integrationconnection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_delivery_attempts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-attempted_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="integrationconnection",
            index=models.Index(
                fields=["organization", "is_active", "type"],
                name="integ_conn_org_active_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationconnection",
            index=models.Index(
                fields=["organization", "created_at"], name="integ_conn_org_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationdeliveryattempt",
            index=models.Index(
                fields=["integration", "attempted_at"],
                name="integ_attempt_conn_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationdeliveryattempt",
            index=models.Index(
                fields=["organization", "attempted_at"],
                name="integ_attempt_org_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationdeliveryattempt",
            index=models.Index(
                fields=["event_type", "attempted_at"],
                name="integ_attempt_event_time_idx",
            ),
        ),
    ]
