# Generated by Django 5.2.13 on 2026-04-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconnection",
            name="event_types",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
